server {
    listen 80;
    server_name vacancy.aismegion.ru;  # или ваш IP, если домена нет

    root /home/;  # папка с собранным React

    index index.html;

    # Обслуживание React SPA
    location / {
        try_files $uri /index.html;
    }

    # Проксирование API-запросов к Node.js
    location /api/ {
        proxy_pass http://localhost:5000/;  # ваш Node.js бэкенд
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}